// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for audiovisual documents */
interface AudiovisualDocumentData {
  /**
   * audiovisual field in *audiovisual*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: audiovisual.audiovisual[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  audiovisual: prismicT.GroupField<
    Simplify<AudiovisualDocumentDataAudiovisualItem>
  >;
}
/**
 * Item in audiovisual → audiovisual
 *
 */
export interface AudiovisualDocumentDataAudiovisualItem {
  /**
   * titulo field in *audiovisual → audiovisual*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: audiovisual.audiovisual[].titulo
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  titulo: prismicT.KeyTextField;
  /**
   * link field in *audiovisual → audiovisual*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: audiovisual.audiovisual[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  link: prismicT.KeyTextField;
}
/**
 * audiovisual document from Prismic
 *
 * - **API ID**: `audiovisual`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AudiovisualDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<AudiovisualDocumentData>,
    "audiovisual",
    Lang
  >;
/** Content for bio documents */
interface BioDocumentData {
  /**
   * title field in *bio*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismicT.RichTextField;
  /**
   * body field in *bio*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismicT.RichTextField;
  /**
   * image field in *bio*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bio.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
}
/**
 * bio document from Prismic
 *
 * - **API ID**: `bio`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BioDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<Simplify<BioDocumentData>, "bio", Lang>;
/** Content for Dektop documents */
interface DektopDocumentData {
  /**
   * desktop field in *Dektop*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: dektop.desktop[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  desktop: prismicT.GroupField<Simplify<DektopDocumentDataDesktopItem>>;
}
/**
 * Item in Dektop → desktop
 *
 */
export interface DektopDocumentDataDesktopItem {
  /**
   * image field in *Dektop → desktop*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: dektop.desktop[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
}
/**
 * Dektop document from Prismic
 *
 * - **API ID**: `dektop`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DektopDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<DektopDocumentData>,
    "dektop",
    Lang
  >;
/** Content for music documents */
interface MusicDocumentData {
  /**
   * music field in *music*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: music.music[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  music: prismicT.GroupField<Simplify<MusicDocumentDataMusicItem>>;
}
/**
 * Item in music → music
 *
 */
export interface MusicDocumentDataMusicItem {
  /**
   * title field in *music → music*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: music.music[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismicT.RichTextField;
  /**
   * image field in *music → music*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: music.music[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
  /**
   * links field in *music → music*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: music.music[].links
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  links: prismicT.RichTextField;
}
/**
 * music document from Prismic
 *
 * - **API ID**: `music`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MusicDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<MusicDocumentData>,
    "music",
    Lang
  >;
/** Content for nube rosa documents */
interface NubeRosaDocumentData {
  /**
   * nube_rosa field in *nube rosa*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: nube_rosa.nube_rosa[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  nube_rosa: prismicT.GroupField<Simplify<NubeRosaDocumentDataNubeRosaItem>>;
}
/**
 * Item in nube rosa → nube_rosa
 *
 */
export interface NubeRosaDocumentDataNubeRosaItem {
  /**
   * title field in *nube rosa → nube_rosa*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nube_rosa.nube_rosa[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * imagen field in *nube rosa → nube_rosa*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nube_rosa.nube_rosa[].imagen
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  imagen: prismicT.ImageField<never>;
  /**
   * text field in *nube rosa → nube_rosa*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nube_rosa.nube_rosa[].text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismicT.RichTextField;
}
/**
 * nube rosa document from Prismic
 *
 * - **API ID**: `nube_rosa`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NubeRosaDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<NubeRosaDocumentData>,
    "nube_rosa",
    Lang
  >;
/** Content for oraculo documents */
interface OraculoDocumentData {
  /**
   * cartas field in *oraculo*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: oraculo.cartas[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  cartas: prismicT.GroupField<Simplify<OraculoDocumentDataCartasItem>>;
}
/**
 * Item in oraculo → cartas
 *
 */
export interface OraculoDocumentDataCartasItem {
  /**
   * carta field in *oraculo → cartas*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: oraculo.cartas[].carta
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  carta: prismicT.ImageField<never>;
}
/**
 * oraculo document from Prismic
 *
 * - **API ID**: `oraculo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OraculoDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<OraculoDocumentData>,
    "oraculo",
    Lang
  >;
/** Content for text documents */
interface TextDocumentData {
  /**
   * title field in *text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * body field in *text*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismicT.RichTextField;
}
/**
 * text document from Prismic
 *
 * - **API ID**: `text`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TextDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<Simplify<TextDocumentData>, "text", Lang>;
/** Content for vision documents */
interface VisionDocumentData {
  /**
   * visiones field in *vision*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: vision.visiones[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  visiones: prismicT.GroupField<Simplify<VisionDocumentDataVisionesItem>>;
}
/**
 * Item in vision → visiones
 *
 */
export interface VisionDocumentDataVisionesItem {
  /**
   * titulo field in *vision → visiones*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision.visiones[].titulo
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  titulo: prismicT.KeyTextField;
  /**
   * imagen field in *vision → visiones*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: vision.visiones[].imagen
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  imagen: prismicT.ImageField<never>;
}
/**
 * vision document from Prismic
 *
 * - **API ID**: `vision`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VisionDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<VisionDocumentData>,
    "vision",
    Lang
  >;
export type AllDocumentTypes =
  | AudiovisualDocument
  | BioDocument
  | DektopDocument
  | MusicDocument
  | NubeRosaDocument
  | OraculoDocument
  | TextDocument
  | VisionDocument;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      AudiovisualDocumentData,
      AudiovisualDocumentDataAudiovisualItem,
      AudiovisualDocument,
      BioDocumentData,
      BioDocument,
      DektopDocumentData,
      DektopDocumentDataDesktopItem,
      DektopDocument,
      MusicDocumentData,
      MusicDocumentDataMusicItem,
      MusicDocument,
      NubeRosaDocumentData,
      NubeRosaDocumentDataNubeRosaItem,
      NubeRosaDocument,
      OraculoDocumentData,
      OraculoDocumentDataCartasItem,
      OraculoDocument,
      TextDocumentData,
      TextDocument,
      VisionDocumentData,
      VisionDocumentDataVisionesItem,
      VisionDocument,
      AllDocumentTypes,
    };
  }
}
